#lang racket
(provide (all-defined-out))
(define (Math display . xml*)
  `(math ((display ,display)) . ,xml*))
(define (MathB . xml*)
  (apply Math "block" xml*))
(define (MathI . xml*)
  (apply Math "inline" xml*))
(define (Mrow . xml*)
  `(mrow . ,xml*))
(define (Mi x) `(mi ,x))
(define (Mn n) `(mn ,n))
(define (Mo op) `(mo ,op))
(define (Mtext text)
  `(mtext ,text))
(define (Msup a b)
  `(msup ,a ,b))
(define (Msub a b)
  `(msub ,a ,b))
(define (Msubsup a b c)
  `(msubsup ,a ,b ,c))
(define (Mfrac a b)
  `(mfrac ,a ,b))
(define (Mfrac0 a b)
  `(mfrac ((linethickness "0")) ,a ,b))
(define (Msqrt a)
  `(msqrt ,a))
(define (Mroot a b)
  `(mroot ,a ,b))
(define (Munder a b)
  `(munder ,a ,b))
(define (Mover a b)
  `(mover ,a ,b))
(define (Munderover a b c)
  `(munderover ,a ,b ,c))
(define (Mtable . r*)
  `(mtable . ,r*))
(define (Mtr . e*)
  `(mtr . ,e*))
(define (Mtd x)
  `(mtd ,x))
(define :a (Mi "a"))
(define :b (Mi "b"))
(define :c (Mi "c"))
(define :d (Mi "d"))
(define :e (Mi "e"))
(define :f (Mi "f"))
(define :g (Mi "g"))
(define :h (Mi "h"))
(define :i (Mi "i"))
(define :j (Mi "j"))
(define :k (Mi "k"))
(define :l (Mi "l"))
(define :m (Mi "m"))
(define :n (Mi "n"))
(define :o (Mi "o"))
(define :p (Mi "p"))
(define :q (Mi "q"))
(define :r (Mi "r"))
(define :s (Mi "s"))
(define :t (Mi "t"))
(define :u (Mi "u"))
(define :v (Mi "v"))
(define :w (Mi "w"))
(define :x (Mi "x"))
(define :y (Mi "y"))
(define :z (Mi "z"))
(define :A (Mi "A"))
(define :B (Mi "B"))
(define :C (Mi "C"))
(define :D (Mi "D"))
(define :E (Mi "E"))
(define :F (Mi "F"))
(define :G (Mi "G"))
(define :H (Mi "H"))
(define :I (Mi "I"))
(define :J (Mi "J"))
(define :K (Mi "K"))
(define :L (Mi "L"))
(define :M (Mi "M"))
(define :N (Mi "N"))
(define :O (Mi "O"))
(define :P (Mi "P"))
(define :Q (Mi "Q"))
(define :R (Mi "R"))
(define :S (Mi "S"))
(define :T (Mi "T"))
(define :U (Mi "U"))
(define :V (Mi "V"))
(define :W (Mi "W"))
(define :X (Mi "X"))
(define :Y (Mi "Y"))
(define :Z (Mi "Z"))
(define :aa (Mi "&aopf;"))
(define :bb (Mi "&bopf;"))
(define :cc (Mi "&copf;"))
(define :dd (Mi "&dopf;"))
(define :ee (Mi "&eopf;"))
(define :ff (Mi "&fopf;"))
(define :gg (Mi "&gopf;"))
(define :hh (Mi "&hopf;"))
(define :ii (Mi "&iopf;"))
(define :jj (Mi "&jopf;"))
(define :kk (Mi "&kopf;"))
(define :ll (Mi "&lopf;"))
(define :mm (Mi "&mopf;"))
(define :nn (Mi "&nopf;"))
(define :oo (Mi "&oopf;"))
(define :pp (Mi "&popf;"))
(define :qq (Mi "&qopf;"))
(define :rr (Mi "&ropf;"))
(define :ss (Mi "&sopf;"))
(define :tt (Mi "&topf;"))
(define :uu (Mi "&uopf;"))
(define :vv (Mi "&vopf;"))
(define :ww (Mi "&wopf;"))
(define :xx (Mi "&xopf;"))
(define :yy (Mi "&yopf;"))
(define :zz (Mi "&zopf;"))
(define :AA (Mi "&Aopf;"))
(define :BB (Mi "&Bopf;"))
(define :CC (Mi "&Copf;"))
(define :DD (Mi "&Dopf;"))
(define :EE (Mi "&Eopf;"))
(define :FF (Mi "&Fopf;"))
(define :GG (Mi "&Gopf;"))
(define :HH (Mi "&Hopf;"))
(define :II (Mi "&Iopf;"))
(define :JJ (Mi "&Jopf;"))
(define :KK (Mi "&Kopf;"))
(define :LL (Mi "&Lopf;"))
(define :MM (Mi "&Mopf;"))
(define :NN (Mi "&Nopf;"))
(define :OO (Mi "&Oopf;"))
(define :PP (Mi "&Popf;"))
(define :QQ (Mi "&Qopf;"))
(define :RR (Mi "&Ropf;"))
(define :SS (Mi "&Sopf;"))
(define :TT (Mi "&Topf;"))
(define :UU (Mi "&Uopf;"))
(define :VV (Mi "&Vopf;"))
(define :WW (Mi "&Wopf;"))
(define :XX (Mi "&Xopf;"))
(define :YY (Mi "&Yopf;"))
(define :ZZ (Mi "&Zopf;"))
(define :alpha (Mi "&alpha;"))
(define :beta (Mi "&beta;"))
(define :gamma (Mi "&gamma;"))
(define :delta (Mi "&delta;"))
(define :epsilon (Mi "&epsilon;"))
(define :zeta (Mi "&zeta;"))
(define :eta (Mi "&eta;"))
(define :theta (Mi "&theta;"))
(define :iota (Mi "&iota;"))
(define :kappa (Mi "&kappa;"))
(define :lambda (Mi "&lambda;"))
(define :mu (Mi "&mu;"))
(define :nu (Mi "&nu;"))
(define :xi (Mi "&xi;"))
(define :omicron (Mi "&omicron;"))
(define :pi (Mi "&pi;"))
(define :rho (Mi "&rho;"))
(define :sigma (Mi "&sigma;"))
(define :tau (Mi "&tau;"))
(define :upsilon (Mi "&upsilon;"))
(define :phi (Mi "&phi;"))
(define :chi (Mi "&chi;"))
(define :psi (Mi "&psi;"))
(define :omega (Mi "&omega;"))
(define :Alpha (Mi "&Alpha;"))
(define :Beta (Mi "&Beta;"))
(define :Gamma (Mi "&Gamma;"))
(define :Delta (Mi "&Delta;"))
(define :Epsilon (Mi "&Epsilon;"))
(define :Zeta (Mi "&Zeta;"))
(define :Eta (Mi "&Eta;"))
(define :Theta (Mi "&Theta;"))
(define :Iota (Mi "&Iota;"))
(define :Kappa (Mi "&Kappa;"))
(define :Lambda (Mi "&Lambda;"))
(define :Mu (Mi "&Mu;"))
(define :Nu (Mi "&Nu;"))
(define :Xi (Mi "&Xi;"))
(define :Omicron (Mi "&Omicron;"))
(define :Pi (Mi "&Pi;"))
(define :Rho (Mi "&Rho;"))
(define :Sigma (Mi "&Sigma;"))
(define :Tau (Mi "&Tau;"))
(define :Upsilon (Mi "&Upsilon;"))
(define :Phi (Mi "&Phi;"))
(define :Chi (Mi "&Chi;"))
(define :Psi (Mi "&Psi;"))
(define :Omega (Mi "&Omega;"))
(define :0 (Mn "0"))
(define :1 (Mn "1"))
(define :2 (Mn "2"))
(define :3 (Mn "3"))
(define :4 (Mn "4"))
(define :5 (Mn "5"))
(define :6 (Mn "6"))
(define :7 (Mn "7"))
(define :8 (Mn "8"))
(define :9 (Mn "9"))
(define :+ (Mo "+"))
(define :- (Mo "&minus;"))
(define :i* (Mo "&it;"))
(define :d* (Mo "&sdot;"))
(define :c* (Mo "&times;"))
(define := (Mo "="))
(define :<= (Mo "&le;"))
(define :>= (Mo "&ge;"))
(define :af (Mo "&af;"))
(define :-> (Mo "&rarr;"))
(define ::-> (Mo "&mapsto;"))
(define :cm (Mo ","))
(define :: (Mo ":"))
(define :_ (Mrow))
(define (: . x*)
  (cond ((null? x*) :_)
        ((null? (cdr x*)) (car x*))
        (else (cons 'mrow x*))))
(define :-1 (Mrow :- :1))
(define (:sqr x)
  (Msup x :2))
(define (:cub x)
  (Msup x :3))
(define :inf (Mo "&infin;"))
(define :sin (Mo "sin"))
(define :cos (Mo "cos"))
(define :tan (Mo "tan"))
(define :fib (Mo "fib"))
(define :..h (Mo "&hellip;"))
(define :..v (Mo "&vellip;"))
(define :..m (Mo "&ctdot;"))
(define :..u (Mo "&utdot;"))
(define :..d (Mo "&dtdot;"))
(define :lim (Mo "lim"))
(define :sum (Mo "&sum;"))
(define :prod (Mo "&prod;"))
(define :lp (Mo "("))
(define :rp (Mo ")"))
(define (:paren . x*)
  (Mrow :lp (apply : x*) :rp))
(define :lp0 '(mo ((stretchy "false")) "("))
(define :rp0 '(mo ((stretchy "false")) ")"))
(define (:paren0 . x*)
  (Mrow :lp0 (apply : x*) :rp0))
(define :lb (Mo "["))
(define :rb (Mo "]"))
(define (:brack . x*)
  (Mrow :lb (apply : x*) :rb))
(define :lb0 '(mo ((stretchy "false")) "["))
(define :rb0 '(mo ((stretchy "false")) "]"))
(define (:brack0 . x*)
  (Mrow :lb0 (apply : x*) :rb0))
(define :lv (Mo "|"))
(define :rv (Mo "|"))
(define (:verti . x*)
  (Mrow :lv (apply : x*) :rv))
(define :lcb (Mo "{"))
(define :rcb (Mo "}"))
(define :! (Mo "!"))
(define (:seq . x*)
  (cond
    ((null? x*) :_)
    ((null? (cdr x*)) (car x*))
    (else
     (let iter ((x (car x*)) (x* (cdr x*)) (r '()))
       (if (null? x*)
           (cons 'mrow (reverse (cons x r)))
           (iter (car x*)
                 (cdr x*)
                 (cons :cm (cons x r))))))))
(define (:tuple . x*)
  (:paren (apply :seq x*)))
(define (:tuple0 . x*)
  (:paren0 (apply :seq x*)))
(define (:list . x*)
  (:brack (apply :seq x*)))
(define (:list0 . x*)
  (:brack0 (apply :seq x*)))
(define (:table l)
  (cons 'mtable
        (map (lambda (r)
               (cons 'mtr (map Mtd r)))
             l)))
(define (:choice l)
  (Mrow :lcb (:table l)))
(define (:matrix l)
  (:brack (:table l)))
(define (:det l)
  (:verti (:table l)))
(define (:ap f . x*)
  (Mrow f :af (apply :tuple x*)))
(define (:ap0 f . x*)
  (Mrow f :af (apply :tuple0 x*)))
(define (:type f A B)
  (Mrow f :: A :-> B))
(define (:Lim x a)
  (Munder :lim (Mrow x :-> a)))
(define (:comb a b)
  (:paren (Mfrac0 a b)))
(define (:deriv x y . z*)
  (:table
   (cons (list x := y)
         (map (lambda (z)
                (list :_ := z))
              z*))))
(define (:Sum a b)
  (Munderover :sum a b))
(define (:Prod a b)
  (Munderover :prod a b))
(define (:inv x)
  (Mfrac :1 x))
(define (:inv0 x)
  (Msup x :-1))
