#lang racket
(provide (all-defined-out))
(define (Math display . xml*)
  `(math ((display ,display)) . ,xml*))
(define (MathB . xml*)
  (apply Math "block" xml*))
(define (MathI . xml*)
  (apply Math "inline" xml*))
(define (Mrow . xml*)
  `(mrow . ,xml*))
(define (Mi x) `(mi ,x))
(define (Mn n) `(mn ,n))
(define (Mo op) `(mo ,op))
(define (Mtext text)
  `(mtext ,text))
(define (Msup a b)
  `(msup ,a ,b))
(define (Msub a b)
  `(msub ,a ,b))
(define (Msubsup a b c)
  `(msubsup ,a ,b ,c))
(define (Mfrac a b)
  `(mfrac ,a ,b))
(define (Msqrt a)
  `(msqrt ,a))
(define (Mroot a b)
  `(mroot ,a ,b))
(define (Munder a b)
  `(munder ,a ,b))
(define (Mover a b)
  `(mover ,a ,b))
(define (Munderover a b c)
  `(munderover ,a ,b ,c))
(define (Mtable . r*)
  `(mtable . ,r*))
(define (Mtr . e*)
  `(mtr . ,e*))
(define (Mtd x)
  `(mtd ,x))
(define nil (Mrow))
(define $a (Mi "a"))
(define $b (Mi "b"))
(define $c (Mi "c"))
(define $d (Mi "d"))
(define $e (Mi "e"))
(define $f (Mi "f"))
(define $g (Mi "g"))
(define $h (Mi "h"))
(define $i (Mi "i"))
(define $j (Mi "j"))
(define $k (Mi "k"))
(define $l (Mi "l"))
(define $m (Mi "m"))
(define $n (Mi "n"))
(define $o (Mi "o"))
(define $p (Mi "p"))
(define $q (Mi "q"))
(define $r (Mi "r"))
(define $s (Mi "s"))
(define $t (Mi "t"))
(define $u (Mi "u"))
(define $v (Mi "v"))
(define $w (Mi "w"))
(define $x (Mi "x"))
(define $y (Mi "y"))
(define $z (Mi "z"))
(define $A (Mi "A"))
(define $B (Mi "B"))
(define $C (Mi "C"))
(define $D (Mi "D"))
(define $E (Mi "E"))
(define $F (Mi "F"))
(define $G (Mi "G"))
(define $H (Mi "H"))
(define $I (Mi "I"))
(define $J (Mi "J"))
(define $K (Mi "K"))
(define $L (Mi "L"))
(define $M (Mi "M"))
(define $N (Mi "N"))
(define $O (Mi "O"))
(define $P (Mi "P"))
(define $Q (Mi "Q"))
(define $R (Mi "R"))
(define $S (Mi "S"))
(define $T (Mi "T"))
(define $U (Mi "U"))
(define $V (Mi "V"))
(define $W (Mi "W"))
(define $X (Mi "X"))
(define $Y (Mi "Y"))
(define $Z (Mi "Z"))
(define $aa (Mi "&aopf;"))
(define $bb (Mi "&bopf;"))
(define $cc (Mi "&copf;"))
(define $dd (Mi "&dopf;"))
(define $ee (Mi "&eopf;"))
(define $ff (Mi "&fopf;"))
(define $gg (Mi "&gopf;"))
(define $hh (Mi "&hopf;"))
(define $ii (Mi "&iopf;"))
(define $jj (Mi "&jopf;"))
(define $kk (Mi "&kopf;"))
(define $ll (Mi "&lopf;"))
(define $mm (Mi "&mopf;"))
(define $nn (Mi "&nopf;"))
(define $oo (Mi "&oopf;"))
(define $pp (Mi "&popf;"))
(define $qq (Mi "&qopf;"))
(define $rr (Mi "&ropf;"))
(define $ss (Mi "&sopf;"))
(define $tt (Mi "&topf;"))
(define $uu (Mi "&uopf;"))
(define $vv (Mi "&vopf;"))
(define $ww (Mi "&wopf;"))
(define $xx (Mi "&xopf;"))
(define $yy (Mi "&yopf;"))
(define $zz (Mi "&zopf;"))
(define $AA (Mi "&Aopf;"))
(define $BB (Mi "&Bopf;"))
(define $CC (Mi "&Copf;"))
(define $DD (Mi "&Dopf;"))
(define $EE (Mi "&Eopf;"))
(define $FF (Mi "&Fopf;"))
(define $GG (Mi "&Gopf;"))
(define $HH (Mi "&Hopf;"))
(define $II (Mi "&Iopf;"))
(define $JJ (Mi "&Jopf;"))
(define $KK (Mi "&Kopf;"))
(define $LL (Mi "&Lopf;"))
(define $MM (Mi "&Mopf;"))
(define $NN (Mi "&Nopf;"))
(define $OO (Mi "&Oopf;"))
(define $PP (Mi "&Popf;"))
(define $QQ (Mi "&Qopf;"))
(define $RR (Mi "&Ropf;"))
(define $SS (Mi "&Sopf;"))
(define $TT (Mi "&Topf;"))
(define $UU (Mi "&Uopf;"))
(define $VV (Mi "&Vopf;"))
(define $WW (Mi "&Wopf;"))
(define $XX (Mi "&Xopf;"))
(define $YY (Mi "&Yopf;"))
(define $ZZ (Mi "&Zopf;"))
(define $alpha (Mi "&alpha;"))
(define $beta (Mi "&beta;"))
(define $gamma (Mi "&gamma;"))
(define $delta (Mi "&delta;"))
(define $epsilon (Mi "&epsilon;"))
(define $zeta (Mi "&zeta;"))
(define $eta (Mi "&eta;"))
(define $theta (Mi "&theta;"))
(define $iota (Mi "&iota;"))
(define $kappa (Mi "&kappa;"))
(define $lambda (Mi "&lambda;"))
(define $mu (Mi "&mu;"))
(define $nu (Mi "&nu;"))
(define $xi (Mi "&xi;"))
(define $omicron (Mi "&omicron;"))
(define $pi (Mi "&pi;"))
(define $rho (Mi "&rho;"))
(define $sigma (Mi "&sigma;"))
(define $tau (Mi "&tau;"))
(define $upsilon (Mi "&upsilon;"))
(define $phi (Mi "&phi;"))
(define $chi (Mi "&chi;"))
(define $psi (Mi "&psi;"))
(define $omega (Mi "&omega;"))
(define $Alpha (Mi "&Alpha;"))
(define $Beta (Mi "&Beta;"))
(define $Gamma (Mi "&Gamma;"))
(define $Delta (Mi "&Delta;"))
(define $Epsilon (Mi "&Epsilon;"))
(define $Zeta (Mi "&Zeta;"))
(define $Eta (Mi "&Eta;"))
(define $Theta (Mi "&Theta;"))
(define $Iota (Mi "&Iota;"))
(define $Kappa (Mi "&Kappa;"))
(define $Lambda (Mi "&Lambda;"))
(define $Mu (Mi "&Mu;"))
(define $Nu (Mi "&Nu;"))
(define $Xi (Mi "&Xi;"))
(define $Omicron (Mi "&Omicron;"))
(define $Pi (Mi "&Pi;"))
(define $Rho (Mi "&Rho;"))
(define $Sigma (Mi "&Sigma;"))
(define $Tau (Mi "&Tau;"))
(define $Upsilon (Mi "&Upsilon;"))
(define $Phi (Mi "&Phi;"))
(define $Chi (Mi "&Chi;"))
(define $Psi (Mi "&Psi;"))
(define $Omega (Mi "&Omega;"))
(define $0 (Mn "0"))
(define $1 (Mn "1"))
(define $2 (Mn "2"))
(define $3 (Mn "3"))
(define $4 (Mn "4"))
(define $5 (Mn "5"))
(define $6 (Mn "6"))
(define $7 (Mn "7"))
(define $8 (Mn "8"))
(define $9 (Mn "9"))
(define $= (Mo "="))
(define $< (Mo "<"))
(define $> (Mo ">"))
(define $<= (Mo "&le;"))
(define $>= (Mo "&ge;"))
(define $- (Mo "&minus;"))
(define $-1 (Mrow $- $1))
(define cm (Mo ","))
(define inf (Mi "&infin;"))
(define af (Mo "&af;"))
(define -> (Mo "&rarr;"))
(define conj (Mo "&and;"))
(define disj (Mo "&or;"))
(define neg (Mo "&not;"))
(define lp (Mo "("))
(define rp (Mo ")"))
(define lp0 '(mo ((stretchy "false")) "("))
(define rp0 '(mo ((stretchy "false")) ")"))
(define lb (Mo "["))
(define rb (Mo "]"))
(define lb0 '(mo ((stretchy "false")) "["))
(define rb0 '(mo ((stretchy "false")) "]"))
(define lc (Mo "{"))
(define rc (Mo "}"))
(define lv (Mo "|"))
(define rv (Mo "|"))
(define lv0 '(mo ((stretchy "false")) "|"))
(define rv0 '(mo ((stretchy "false")) "|"))
(define ..h (Mo "&hellip;"))
(define ..v (Mo "&vellip;"))
(define ..c (Mo "&ctdot;"))
(define ..u (Mo "&utdot;"))
(define ..d (Mo "&dtdot;"))
(define (: . x*)
  (cond
    ((null? x*) nil)
    ((null? (cdr x*)) (car x*))
    (else `(mrow . ,x*))))
(define ((seq o) x . x*)
  (if (null? x*)
      x
      (let iter ((x x) (x* x*) (r '()))
        (if (null? x*)
            (cons 'mrow (reverse (cons x r)))
            (iter (car x*)
                  (cdr x*)
                  (cons o (cons x r)))))))
(define (seq0 o)
  (let ((seqo (seq o)))
    (lambda (x y . z*)
      (apply seqo x y z*))))
(define &cm (seq cm))
(define &= (seq0 $=))
(define &>= (seq0 $>=))
(define &<= (seq0 $<=))
(define &< (seq0 $<))
(define &+ (seq '(mo "+")))
(define &-
  (let ((seq- (seq $-)))
    (lambda (x . x*)
      (if (null? x*)
          (Mrow $- x)
          (apply seq- x x*)))))
(define i* (seq '(mo "&it;")))
(define d* (seq '(mo "&sdot;")))
(define c* (seq '(mo "&times;")))
(define (^ a b)
  (Msup a b))
(define (_ a b)
  (Msub a b))
(define (_^ a b c)
  (Msubsup a b c))
(define (~ a b)
  (Mfrac a b))
(define (inv x)
  (~ $1 x))
(define (pare x)
  (Mrow lp x rp))
(define (par0 x)
  (Mrow lp0 x rp0))
(define (brac x)
  (Mrow lb x rb))
(define (bra0 x)
  (Mrow lb0 x rb0))
(define (curb x)
  (Mrow lc x rc))
(define (vert x)
  (Mrow lv x rv))
(define (ver0 x)
  (Mrow lv0 x rv0))
(define (Mfra0 a b)
  `(mfrac ((linethickness "0")) ,a ,b))
(define (comb a b)
  (pare (Mfra0 a b)))
(define (fact n)
  (Mrow n '(mo "!")))
(define (tup . x*)
  (if (null? x*)
      '(mrow (mo "(") (mo ")"))
      (pare (apply &cm x*))))
(define (tu0 . x*)
  (if (null? x*)
      '(mrow (mo ((stretchy "false")) "(")
             (mo ((stretchy "false")) ")"))
      (par0 (apply &cm x*))))
(define (lis . x*)
  (if (null? x*)
      '(mrow (mo "[") (mo "]"))
      (brac (apply &cm x*))))
(define (li0 . x*)
  (if (null? x*)
      '(mrow (mo ((stretchy "false")) "[")
             (mo ((stretchy "false")) "]"))
      (bra0 (apply &cm x*))))
(define (sum u o e)
  (Mrow (Munderover '(mo "&sum;") u o) e))
(define (prod u o e)
  (Mrow (Munderover '(mo "&prod;") u o) e))
(define (lim x a e)
  (Mrow (Munder '(mo "lim")
                (Mrow x -> a))
        e))
(define (mtab l)
  (cons 'mtable
        (map (lambda (r)
               (cons 'mtr (map Mtd r)))
             l)))
(define (choice l)
  (Mrow lc (mtab l)))
(define (mat l)
  (brac (mtab l)))
(define (det l)
  (vert (mtab l)))
(define (deriv x y . z*)
  (mtab
   (cons (list x $= y)
         (map (lambda (z)
                (list nil $= z))
              z*))))
(define (ap f x)
  (Mrow f af x))
(define (@ . x*)
  (par0 (apply : x*)))
