#lang racket
(provide (all-defined-out))
(define (Math display . xml*)
  `(math ((display ,display)) . ,xml*))
(define (MathB . xml*)
  (apply Math "block" xml*))
(define (MathI . xml*)
  (apply Math "inline" xml*))
(define (Mrow . xml*)
  `(mrow . ,xml*))
(define (Mi x) `(mi ,x))
(define (Mn n) `(mn ,n))
(define (Mo op) `(mo ,op))
(define (Mtext text)
  `(mtext ,text))
(define (Msup a b)
  `(msup ,a ,b))
(define (Msub a b)
  `(msub ,a ,b))
(define (Msubsup a b c)
  `(msubsup ,a ,b ,c))
(define (Mfrac a b)
  `(mfrac ,a ,b))
(define (Msqrt a)
  `(msqrt ,a))
(define (Mroot a b)
  `(mroot ,a ,b))
(define (Munder a b)
  `(munder ,a ,b))
(define (Mover a b)
  `(mover ,a ,b))
(define (Munderover a b c)
  `(munderover ,a ,b ,c))
(define (Mtable . r*)
  `(mtable . ,r*))
(define (Mtr . e*)
  `(mtr . ,e*))
(define (Mtd x)
  `(mtd ,x))
(define (^ a b)
  (Msup a b))
(define (~ a b)
  (Mfrac a b))
(define (_ a b)
  (Msub a b))
(define (_^ a b c)
  (Msubsup a b c))
(define $a (Mi "a"))
(define $b (Mi "b"))
(define $c (Mi "c"))
(define $d (Mi "d"))
(define $e (Mi "e"))
(define $f (Mi "f"))
(define $g (Mi "g"))
(define $h (Mi "h"))
(define $i (Mi "i"))
(define $j (Mi "j"))
(define $k (Mi "k"))
(define $l (Mi "l"))
(define $m (Mi "m"))
(define $n (Mi "n"))
(define $o (Mi "o"))
(define $p (Mi "p"))
(define $q (Mi "q"))
(define $r (Mi "r"))
(define $s (Mi "s"))
(define $t (Mi "t"))
(define $u (Mi "u"))
(define $v (Mi "v"))
(define $w (Mi "w"))
(define $x (Mi "x"))
(define $y (Mi "y"))
(define $z (Mi "z"))
(define $A (Mi "A"))
(define $B (Mi "B"))
(define $C (Mi "C"))
(define $D (Mi "D"))
(define $E (Mi "E"))
(define $F (Mi "F"))
(define $G (Mi "G"))
(define $H (Mi "H"))
(define $I (Mi "I"))
(define $J (Mi "J"))
(define $K (Mi "K"))
(define $L (Mi "L"))
(define $M (Mi "M"))
(define $N (Mi "N"))
(define $O (Mi "O"))
(define $P (Mi "P"))
(define $Q (Mi "Q"))
(define $R (Mi "R"))
(define $S (Mi "S"))
(define $T (Mi "T"))
(define $U (Mi "U"))
(define $V (Mi "V"))
(define $W (Mi "W"))
(define $X (Mi "X"))
(define $Y (Mi "Y"))
(define $Z (Mi "Z"))
(define $aa (Mi "&aopf;"))
(define $bb (Mi "&bopf;"))
(define $cc (Mi "&copf;"))
(define $dd (Mi "&dopf;"))
(define $ee (Mi "&eopf;"))
(define $ff (Mi "&fopf;"))
(define $gg (Mi "&gopf;"))
(define $hh (Mi "&hopf;"))
(define $ii (Mi "&iopf;"))
(define $jj (Mi "&jopf;"))
(define $kk (Mi "&kopf;"))
(define $ll (Mi "&lopf;"))
(define $mm (Mi "&mopf;"))
(define $nn (Mi "&nopf;"))
(define $oo (Mi "&oopf;"))
(define $pp (Mi "&popf;"))
(define $qq (Mi "&qopf;"))
(define $rr (Mi "&ropf;"))
(define $ss (Mi "&sopf;"))
(define $tt (Mi "&topf;"))
(define $uu (Mi "&uopf;"))
(define $vv (Mi "&vopf;"))
(define $ww (Mi "&wopf;"))
(define $xx (Mi "&xopf;"))
(define $yy (Mi "&yopf;"))
(define $zz (Mi "&zopf;"))
(define $AA (Mi "&Aopf;"))
(define $BB (Mi "&Bopf;"))
(define $CC (Mi "&Copf;"))
(define $DD (Mi "&Dopf;"))
(define $EE (Mi "&Eopf;"))
(define $FF (Mi "&Fopf;"))
(define $GG (Mi "&Gopf;"))
(define $HH (Mi "&Hopf;"))
(define $II (Mi "&Iopf;"))
(define $JJ (Mi "&Jopf;"))
(define $KK (Mi "&Kopf;"))
(define $LL (Mi "&Lopf;"))
(define $MM (Mi "&Mopf;"))
(define $NN (Mi "&Nopf;"))
(define $OO (Mi "&Oopf;"))
(define $PP (Mi "&Popf;"))
(define $QQ (Mi "&Qopf;"))
(define $RR (Mi "&Ropf;"))
(define $SS (Mi "&Sopf;"))
(define $TT (Mi "&Topf;"))
(define $UU (Mi "&Uopf;"))
(define $VV (Mi "&Vopf;"))
(define $WW (Mi "&Wopf;"))
(define $XX (Mi "&Xopf;"))
(define $YY (Mi "&Yopf;"))
(define $ZZ (Mi "&Zopf;"))
(define $alpha (Mi "&alpha;"))
(define $beta (Mi "&beta;"))
(define $gamma (Mi "&gamma;"))
(define $delta (Mi "&delta;"))
(define $epsilon (Mi "&epsilon;"))
(define $zeta (Mi "&zeta;"))
(define $eta (Mi "&eta;"))
(define $theta (Mi "&theta;"))
(define $iota (Mi "&iota;"))
(define $kappa (Mi "&kappa;"))
(define $lambda (Mi "&lambda;"))
(define $mu (Mi "&mu;"))
(define $nu (Mi "&nu;"))
(define $xi (Mi "&xi;"))
(define $omicron (Mi "&omicron;"))
(define $pi (Mi "&pi;"))
(define $rho (Mi "&rho;"))
(define $sigma (Mi "&sigma;"))
(define $tau (Mi "&tau;"))
(define $upsilon (Mi "&upsilon;"))
(define $phi (Mi "&phi;"))
(define $chi (Mi "&chi;"))
(define $psi (Mi "&psi;"))
(define $omega (Mi "&omega;"))
(define $Alpha (Mi "&Alpha;"))
(define $Beta (Mi "&Beta;"))
(define $Gamma (Mi "&Gamma;"))
(define $Delta (Mi "&Delta;"))
(define $Epsilon (Mi "&Epsilon;"))
(define $Zeta (Mi "&Zeta;"))
(define $Eta (Mi "&Eta;"))
(define $Theta (Mi "&Theta;"))
(define $Iota (Mi "&Iota;"))
(define $Kappa (Mi "&Kappa;"))
(define $Lambda (Mi "&Lambda;"))
(define $Mu (Mi "&Mu;"))
(define $Nu (Mi "&Nu;"))
(define $Xi (Mi "&Xi;"))
(define $Omicron (Mi "&Omicron;"))
(define $Pi (Mi "&Pi;"))
(define $Rho (Mi "&Rho;"))
(define $Sigma (Mi "&Sigma;"))
(define $Tau (Mi "&Tau;"))
(define $Upsilon (Mi "&Upsilon;"))
(define $Phi (Mi "&Phi;"))
(define $Chi (Mi "&Chi;"))
(define $Psi (Mi "&Psi;"))
(define $Omega (Mi "&Omega;"))
(define $0 (Mn "0"))
(define $1 (Mn "1"))
(define $2 (Mn "2"))
(define $3 (Mn "3"))
(define $4 (Mn "4"))
(define $5 (Mn "5"))
(define $6 (Mn "6"))
(define $7 (Mn "7"))
(define $8 (Mn "8"))
(define $9 (Mn "9"))
(define $ (Mrow))
(define $= (Mo "="))
(define $< (Mo "<"))
(define $> (Mo ">"))
(define $<= (Mo "&le;"))
(define $>= (Mo "&ge;"))
(define $+ (Mo "+"))
(define $- (Mo "&minus;"))
(define $+- (Mo "&plusmn;"))
(define $-+ (Mo "&mnplus;"))
(define $i* (Mo "&it;"))
(define $d* (Mo "&sdot;"))
(define $c* (Mo "&times;"))
(define $cm (Mo ","))
(define $inf (Mi "&infin;"))
(define $af (Mo "&af;"))
(define $-> (Mo "&rarr;"))
(define $->0 '(mo ((lspace "0") (rspace "0")) "&rarr;"))
(define $lp (Mo "("))
(define $rp (Mo ")"))
(define $lp0 '(mo ((stretchy "false")) "("))
(define $rp0 '(mo ((stretchy "false")) ")"))
(define $lb (Mo "["))
(define $rb (Mo "]"))
(define $lb0 '(mo ((stretchy "false")) "["))
(define $rb0 '(mo ((stretchy "false")) "]"))
(define $lc (Mo "{"))
(define $rc (Mo "}"))
(define $lv (Mo "|"))
(define $rv (Mo "|"))
(define $lv0 '(mo ((stretchy "false")) "|"))
(define $rv0 '(mo ((stretchy "false")) "|"))
(define $la (Mo "&lang;"))
(define $ra (Mo "&rang;"))
(define $la0 '(mo ((stretchy "false")) "&lang;"))
(define $ra0 '(mo ((stretchy "false")) "&rang;"))
(define $ld (Mo "&Vert;"))
(define $rd (Mo "&Vert;"))
(define $ld0 '(mo ((stretchy "false")) "&Vert;"))
(define $rd0 '(mo ((stretchy "false")) "&Vert;"))
(define $..h (Mo "&hellip;"))
(define $..v (Mo "&vellip;"))
(define $..c (Mo "&ctdot;"))
(define $..u (Mo "&utdot;"))
(define $..d (Mo "&dtdot;"))
(define $conj (Mo "&and;"))
(define $disj (Mo "&or;"))
(define $neg (Mo "&not;"))
(define (: . x*)
  (cond
    ((null? x*) $)
    ((null? (cdr x*)) (car x*))
    (else `(mrow . ,x*))))
(define ((apply-op op n u) . x*)
  (cond
    ((null? x*) (n))
    ((null? (cdr x*)) (u (car x*)))
    (else
     (let iter ((x (car x*)) (x* (cdr x*)) (r '()))
       (if (null? x*)
           (cons 'mrow (reverse (cons x r)))
           (iter (car x*)
                 (cdr x*)
                 (cons op (cons x r))))))))
(define &cm
  (apply-op $cm
    (lambda () $)
    (lambda (x) x)))
(define (&cm1 x)
  (Mrow $cm x))
(define &+
  (apply-op $+
    (lambda () $0)
    (lambda (x) x)))
(define (&+1 x)
  (Mrow $+ x))
(define &-
  (apply-op $-
    (lambda () (error '&- ""))
    (lambda (x) (Mrow $- x))))
(define &+-
  (apply-op $+-
    (lambda () (error '&+- ""))
    (lambda (x) (error '&+- "~s" x))))
(define &-+
  (apply-op $-+
    (lambda () (error '&-+ ""))
    (lambda (x) (error '&-+ "~s" x))))
(define &i*
  (apply-op $i*
    (lambda () $1)
    (lambda (x) x)))
(define &d*
  (apply-op $d*
    (lambda () $1)
    (lambda (x) x)))
(define &c*
  (apply-op $c*
    (lambda () $1)
    (lambda (x) x)))
(define &=
  (apply-op $=
    (lambda () (error '&= ""))
    (lambda (x) (error '&= "~s" x))))
(define &<
  (apply-op $<
    (lambda () (error '&< ""))
    (lambda (x) (error '&< "~s" x))))
(define &<=
  (apply-op $<=
    (lambda () (error '&<= ""))
    (lambda (x) (error '&<= "~s" x))))
(define &>
  (apply-op $>
    (lambda () (error '&> ""))
    (lambda (x) (error '&> "~s" x))))
(define &>=
  (apply-op $>=
    (lambda () (error '&>= ""))
    (lambda (x) (error '&>= "~s" x))))
(define (pare x)
  (Mrow $lp x $rp))
(define (par0 x)
  (Mrow $lp0 x $rp0))
(define (@ . x*)
  (par0 (apply : x*)))
(define (brac x)
  (Mrow $lb x $rb))
(define (bra0 x)
  (Mrow $lb0 x $rb0))
(define (curb x)
  (Mrow $lc x $rc))
(define (vert x)
  (Mrow $lv x $rv))
(define (ver0 x)
  (Mrow $lv0 x $rv0))
(define (angb x)
  (Mrow $la x $ra))
(define (ang0 x)
  (Mrow $la0 x $ra0))
(define (dver x)
  (Mrow $ld x $rd))
(define (dve0 x)
  (Mrow $ld0 x $rd0))
(define (Mfra0 a b)
  `(mfrac ((linethickness "0")) ,a ,b))
(define (comb a b)
  (pare (Mfra0 a b)))
(define (fact n)
  (Mrow n '(mo "!")))
(define (&abs x)
  (ver0 x))
(define (inner* a b)
  (ang0
   (Mrow a '(mo ((lspace "0") (rspace "0")) "|") b)))
(define (norm x)
  (dve0 x))
(define (lim x a e)
  (Mrow (Munder '(mo "lim")
                (Mrow x $->0 a))
        e))
(define (sum u o e)
  (Mrow (Munderover '(mo "&sum;") u o) e))
(define (prod u o e)
  (Mrow (Munderover '(mo "&prod;") u o) e))
(define (mtab l)
  (cons 'mtable
        (map (lambda (r)
               (cons 'mtr (map Mtd r)))
             l)))
(define (choice l)
  (Mrow $lc (mtab l)))
(define (mat l)
  (brac (mtab l)))
(define (det l)
  (vert (mtab l)))
(define (deriv x y . z*)
  (mtab
   (cons (list x $= y)
         (map (lambda (z)
                (list $ $= z))
              z*))))
(define (tup . x*)
  (pare (apply &cm x*)))
(define (tu0 . x*)
  (par0 (apply &cm x*)))
(define (lis . x*)
  (brac (apply &cm x*)))
(define (li0 . x*)
  (bra0 (apply &cm x*)))
(define (ap f x)
  (Mrow f $af x))
(define ((app f) x)
  (ap f (pare x)))
(define ((ap0 f) x)
  (ap f (par0 x)))
(define ((apply-fun f) . x*)
  (ap f (apply tup x*)))
(define ((apply-fu0 f) . x*)
  (ap f (apply tu0 x*)))
